#' @description merge a list in which are all data.frame with one common 
#' rowname or one common column number
#' @name cbindList
#' @title cbindList
#' @param List a list of data frame.
#' @param ID  The number of column, or the column name that need to be refered. 
#' If ID = 0, then the row names of each data frame will be used.
#' @param replace The value to replace the NAs taht generated by cbind of data frame.
#' @param includeColId Logical. Include the refered column if it is TRUE
#' @param sep seperation character of the column names in the data frame 
#' and the corresponding list index. The default is sep = ".". 
#' @return A combined data frame, in which the colnames are the colnames 
#' in the original data frame and corresponding list index
#' @examples 
#' # The zeros/ones matrix
#' a = data.frame(a = letters[1:5], b = rnorm(5))
#' b = data.frame(a = letters[3:7], c = rnorm(5))
#' x = list(a, b)
#' cbindList(List = x, ID = 1)
#' cbindList(List = x, ID = 0)
#' cbindList(List = x, ID = "a")
#' cbindList(List = x, ID = "a", replace = 0)
#' cbindList(List = x, ID = "a", replace = 0, includeColId = TRUE)
#' cbindList(List = x, ID = "a", replace = 0, includeColId = TRUE, sep = "_")
#' @export
cbindList = function(List, ID = 0, replace = NA, includeColId = F, sep = "."){
  stopifnot(is.list(List))
  cName = Reduce("intersect", lapply(List, colnames))
  stopifnot(is.numeric(ID) | (is.character(ID) & (ID %in% cName)))
  # ID is the column name, id is the index of the column
  if (is.numeric(ID)){
    if (ID == 0){
      List = lapply(List, function(x) cbind(rowName = rownames(x), x))
      ID = 1
    }
    id = ID
    ID = colnames(List[[1]])[ID]
  } else {
    id = match(ID, colnames(List[[1]]))
  }
  # use the common row names
  rName = unique(unlist(lapply(List, function(i) {i[,id]})))
  t = data.frame(row.names = rName)
  y = lapply(List, function(i) {
    i = i[match(rName, i[,id]),,drop = F]
    rownames(i) = rName
    return(i)
  })
  nm0 = paste0(sep, 1:length(y))
  y = lapply(1:length(y),function(i){
    colnames(y[[i]]) = paste0(colnames(y[[i]]), nm0[i])
    return(y[[i]])})
  # cbind all data.frame in the list
  y = Reduce(cbind, y) 
  # remove the refered column
  if(!includeColId){
    y = y[, !colnames(y) %in% paste0(ID, nm0)]
  }
  # replace NA
  if(!is.na(replace)) y[is.na(y)] = replace
  return(y)
}
