#' @name MethodsFunction-class
#' @title MethodsFunction-class
#' @keywords internal
#' @description MethodsFunction is an S3 class
setOldClass("MethodsFunction")

# fcnS is an S4 class
# fcnS includes a list of function and corresponding function S3/S4 method names info (MethodsFunction)
setClass("fcnS", slots = list(fcn = "list", fName = "MethodsFunction"))


#' @title Generating functionInfo object\cr
#' @description FunctionInfo is an S4 class and a function to generate functionInfo object.
#' @param funName character, the function name.
#' @param typeof character, the result generated by typeof() function.
#' @param S3S4  logical, whether the results of .S3methods() and .S4methods() exist.
#' @param fcn function, the result shown by print.function() directly.
#' @param fS3 fcnS object, the information of S3 methods.
#' @param fS4 fcnS object, the information of S4 mehtods.
# @describeIn functionInfo set a \code{functionInfo} class.
#' @return a functionInfo object
#' @examples
#' functionInfo()
#' @export
functionInfo = setClass(Class = "functionInfo",
                        slots = list(funName = "character", typeof = "character",
                                     S3S4 = "logical", fcn = "function",
                                     fS3 = "fcnS", fS4 = "fcnS"))


#' @title Finding function source code\cr
#' @description funCode function is to obtain the source code of an R function
#' @param f a function name with or without quotation
#' @param pattern  regular expression to match the object class.
#' @param envir environment to search
#' @return A \code{\link{functionInfo}} object, containing the function name,
#' function type, whether containing S3 or S4 methods, dirrect function source,
#' S3 methods info, and S4 methods info.
#' @export
#' @examples {
#' \dontrun{
#' # The source of print
#' funCode(print)
#' funCode("print")
#'
#' # The source of funCode
#' funCode(funCode)
#'
#' # The source of plot for data.frame
#' funCode("plot", "data.frame")
#' }
#' }
funCode = function(f = character(), pattern = NULL,
                   envir = topenv(parent.frame())){
  # get a function name string (f) and a real function (fcn).
  if (is.character(f)) {
    fcn <- get(f, mode = "function", envir = envir, inherits = TRUE)
  } else if (is.function(f)){
    fcn = f
    f = deparse(substitute(f)) # not working outside the function
  }
  type = typeof(fcn)
  fNameS3 = suppressWarnings(.S3methods(f)) # S3 methods
  fNameS4 = .S4methods(f) # S4 methods

  typeof = type
  S3S4 = c(S3 = length(fNameS3)>0, S4 = length(fNameS4)>0)
  fcnS3 = fcnS4 = list()
  if (S3S4[[1]]){
    names(fNameS3) = sub(paste0(f, "."), "", as.character(fNameS3))
    id = setNames(object = names(fNameS3), nm = names(fNameS3))
    fcnS3 = lapply(id, function(x) {
      getS3method(f = f, class = x, optional = TRUE, envir = envir)})
  }
  if (S3S4[[2]]){
    names(fNameS4) = fNameS4
    sig = strSplit(strSplit(fNameS4, "-")[,1], ",")[,-1, drop = F]
    id = setNames(object = 1:length(fNameS4),
                  nm = apply(sig, 1, paste, collapse = ","))
    fcnS4 = lapply(id, function(x) getMethod(f, signature = sig[x,]))
    names(fNameS4) = names(id)
  }
  # filtering
  if (!is.null(pattern)){
    id3 = grep(pattern, fNameS3)
    id4 = grep(pattern, fNameS4)
    fcnS3 = fcnS3[id3]
    fcnS4 = fcnS4[id4]
  }
  # message
  if (is.element(typeof(fcn), c("special", "builtin"))){
    message(".Primitive and .Internal can be shown by pryr::show_c_source()\n")
  }
  resF = new("functionInfo", funName = f,
             typeof = typeof, S3S4 = S3S4, fcn = fcn,
             fS3 = new("fcnS", fcn = fcnS3, fName = fNameS3),
             fS4 = new("fcnS", fcn = fcnS4, fName = fNameS4))
  return(resF)
}


# @name show
#' @title show,functionInfo-method\cr
#' @aliases  show,functionInfo-method
#' @param object an object of functionInfo class
#' @describeIn functionInfo Show the S3 method names in
#' object@@fS3 and S4 method names in object@@fS4
#' @export
setMethod("show", signature = "functionInfo", function(object) {
  # funName = as.character(substitute(object))
  cat(object@funName, "= ")
  if(length(object@fcn)){
    print(object@fcn)
  }
  show(list(functionS3 = object@fS3@fName,
            functionS4 = object@fS4@fName))
})


