# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Just for test
#' @param x An Interger
#' @return An nterger by x + 1
#' @export
timesTwo <- function(x) {
    .Call('_funcTools_timesTwo', PACKAGE = 'funcTools', x)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('_funcTools_RcppExport_registerCCallable', PACKAGE = 'funcTools')
})
